modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
  issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
  modId="mysticalagriculture"
  version="${file.jarVersion}"
  displayName="Mystical Agriculture"
  # updateJSONURL="http://myurl.me/"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture"
  # logoFile="examplemod.png"
  authors="BlakeBr0"
  credits="Mark719, xun468, Cavemanrockx"
  description='''
  Grow all your resources!
  '''

  [[dependencies.mysticalagriculture]]
      modId="forge"
      mandatory=true
      versionRange="[34.0,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.mysticalagriculture]]
      modId="minecraft"
      mandatory=true
      versionRange="[1.16.3,1.17)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.mysticalagriculture]]
      modId="cucumber"
      mandatory=true
      versionRange="[4.1.2,)"
      ordering="NONE"
      side="BOTH"